### ISSUE TITLE
Please make old google code wiki content accessible in github

### ISSUE THREAD

**Issue by anaran** [CADbloke/google-diff-match-patch#106]

**Comment by anaran** [comment]
Been there, done that.

The old wiki content is now available at https://github.com/CADbloke/google-diff-match-patch/wiki

@CADbloke @mz2 @JanX2 @NeilFraser I found an earlier ["Objective C Port"](https://github.com/JanX2/google-diff-match-patch-git-svn) of the project which seems to lack the wiki branch.

I just wanted to make you all aware of it.

**Comment by CADbloke** [comment]
@anaran Thanks!
